import React from 'react';
import {StyleSheet} from 'react-native';
import Colors from '../Colors/colors';
import {
  heightPercentageToDP as hp,
  widthPercentageToDP as wp,
} from 'react-native-responsive-screen';
export const styles = StyleSheet.create({
  headContainer: {
    flex: 1,
    width: '100%',
    height: '100%',
    // alignItems: 'center',
    backgroundColor: Colors.white,
  },
  mainContainer: {
    // flex: 1,
    width: '100%',
    alignItems: 'center',
    backgroundColor: Colors.white,
  },
  unitDetailContainer: {
    marginTop: '4%',
    width: '95%',
    height: 180,
    elevation: 2,
    backgroundColor: Colors.backgroundColor,
    padding: '5%',
  },
  Unit_DetailsStyle: {
    fontFamily: 'Poppins-Medium',
    fontWeight: '500',
    fontSize: 18,
    color: Colors.themeColor,
  },
  mainBoxContainer: {
    flexDirection: 'row',
    width: '100%',
    height: 150,
  },
  firstContainer: {
    width: '50%',
    height: 150,
  },
  secondContainer: {
    width: '50%',
    height: 150,
  },
  rowContainer: {
    flexDirection: 'row',
    paddingVertical: 10,
  },
  headingText: {
    fontFamily: 'Roboto-Regular',
    fontWeight: '400',
    width: '30%',
    fontSize: 14,
    color: Colors.themeColor,
  },
  headingText1: {
    fontFamily: 'Roboto-Regular',
    fontWeight: '400',
    width: '60%',
    fontSize: 14,
    color: Colors.themeColor,
  },
  answerText: {
    fontFamily: 'Roboto-Regular',
    fontWeight: '400',
    fontSize: 14,
    color: Colors.textGrayColor,
  },
  optionsContainer: {
    flexDirection: 'row',
    paddingVertical: 7,
    width: '55%',
    padding: 5,
    backgroundColor: Colors.backgroundColor,
    borderRadius: 5,
  },
  selectedOption: {
    padding: 10,
    paddingVertical: 5,
    backgroundColor: Colors.backgroundColor,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 5,
  },
  selectedOption1: {
    padding: 10,
    paddingVertical: 5,
    backgroundColor: Colors.backgroundColor,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 12,
    borderRadius: 5,
  },
  optionText: {
    fontFamily: 'Poppins-Regular',
    fontWeight: '500',
  },
  rowButtonStyle: {
    paddingLeft: '3%',
    paddingTop: '5%',
  },
  paymentDetailContainer: {
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  thirdContainer: {
    width: '95%',
    height: 150,
    padding: '2%',
  },
  headingTextPayement: {
    fontFamily: 'Roboto-Medium',
    fontWeight: '700',
    width: '28%',
    fontSize: 14,
    color: Colors.themeColor,
  },
  headingText1Payement: {
    fontFamily: 'Roboto-Regular',
    fontWeight: '400',
    width: '60%',
    fontSize: 4,
    color: Colors.themeColor,
  },
  answerTextPayement: {
    fontFamily: 'Roboto-Regular',
    fontWeight: '400',
    width: '76%',
    fontSize: 13,
    color: Colors.textGrayColor,
  },
  rowContainerPayment: {
    flexDirection: 'row',
    paddingVertical: 10,
  },
  paidTextStyle: {
    fontFamily: 'Roboto-Medium',
    fontWeight: '700',
    color: Colors.white,
    marginLeft: 10,
  },
  paidLeftTextStyle: {
    fontFamily: 'Roboto-Medium',
    fontWeight: '700',
    color: Colors.themeColor,
    marginLeft: 10,
  },
  paidContainer: {
    height: 44,
    width: '32%',
    backgroundColor: Colors.greenColor,
    justifyContent: 'center',
    // alignItems: 'center',
  },
  paidLeftContainer: {
    height: 44,
    width: '58%',
    backgroundColor: Colors.li8GreenColor,
    justifyContent: 'center',
  },
  paidStatusContainer: {
    height: 44,
    width: '90%',
    flexDirection: 'row',
  },
  paymentPlanContainer: {
    marginTop: '5%',
    height: 44,
    width: '90%',
    flexDirection: 'row',
    elevation: 3,
    backgroundColor: Colors.white,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  paymentPlanTextStyle: {
    fontFamily: 'Roboto-Medium',
    fontWeight: '500',
    fontSize: 18,
    color: Colors.themeColor,
    marginRight: 12,
  },
  filesContainer: {
    width: '100%',
    // padding:'5%',
    // paddingLeft:'5%'
  },
  rowDocumentStyle: {
    flexDirection: 'row',
    paddingLeft: '5%',
  },
  documentText: {
    marginLeft: 10,
    fontFamily: 'Poppins-Regular',
    fontWeight: '500',
    fontSize: 14,
    color: Colors.themeColor,
  },
  ImageSliderContainer: {
    height: 205,
    width: wp('70%'),
    marginRight: 15,
    // padding:7,
    elevation: 5,
    backgroundColor: Colors.white,
  },
  progress_container: {
    width: '92%',
    height: 7,
    backgroundColor: Colors.progressBackground,
  },
  progress_inner: {
    width: '90%',
    height: 7,
    backgroundColor: Colors.progressColor,
  },
  progressBarContainer: {
    width: '90%',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 10,
    marginLeft: 10,
    marginBottom: 20,
  },
  progressText: {
    fontFamily: 'Poppins-Bold',
    // fontWeight: '500',
    fontSize: 12,
    color: Colors.themeColor,
  },
  modalCrossText: {
    fontFamily: 'Poppins-Medium',
    // fontWeight: '500',
    fontSize: 14,
    color: Colors.themeColor,
    marginRight: 5,
  },
  modalCloseContainer1: {
    flexDirection: 'row',
    padding: 10,
  },
  modalCloseContainer: {
    alignItems: 'flex-end',
  },
  tableHeadingStyle: {
    fontFamily: 'Roboto-Medium',
    fontWeight: '700',
    fontSize: 14,
    color: Colors.white,
  },
  tableHeadingStyle1: {
    fontFamily: 'Roboto-Regular',
    fontWeight: '400',
    fontSize: 14,
    color: Colors.textGrayColor,
  },
  tableHeadingContainer: {
    height: 26,
    width: '100%',
    flexDirection: 'row',
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,

    backgroundColor: Colors.progressColor,
  },
  columStyle1: {
    width: '43%',
    padding: 2,
    paddingLeft: 8,
  },
  columStyle2: {
    width: '37%',
    padding: 2,
  },
  columStyle3: {
    width: '20%',
    padding: 2,
  },
  tableHeadingContainer1: {
    height: 56,
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  paymentDataContainer: {
    width: '95%',
    height: 200,
    borderColor: Colors.tableBorderColor,
    borderWidth: 1,
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
  },
  paymentDataContainer1: {
    width: '95%',
    height: 500,
    borderColor: Colors.tableBorderColor,
    borderWidth: 1,
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
  },
});
